### ISSUE TITLE
Shadcn-Nuxt  Unocss Support

### ISSUE THREAD

**Issue by kingtimm** [hyoban-template/shadcn-vue-unocss-starter#10]
Hi

Curious if others have had any luck getting this to work in nuxt with [shadcn-nuxt](https://www.shadcn-vue.com/docs/installation/nuxt).

inspired by:

- https://github.com/radix-vue/shadcn-vue/issues/34#issuecomment-1989396013
- https://github.com/hyoban/shadcn-vue-unocss-starter

I created this attempt at a nuxt version of the vue starter. https://github.com/kingtimm/uno-shadcn-nuxt-src

It still looks like unocss is not including button's styles (dark background, rounded edges). Here's a screenshot of nuxt (port 3000) vs. the starter (5173)

![image](https://github.com/hyoban-template/shadcn-vue-unocss-starter/assets/422920/23643c13-9624-434f-8d98-d5c73529cfc4)

**Comment by hyoban** [comment]
I have no idea why this order matter, but you can try remove tailwindcss and change config to:

```ts
import { defineConfig, presetUno } from 'unocss'
import presetAnimations from 'unocss-preset-animations'
import { presetShadcn } from 'unocss-preset-shadcn'

export default defineConfig({
  presets: [
    presetUno(),
    presetAnimations(),
    presetShadcn(),
  ],
  content: {
    pipeline: {
      include: [
        // include js/ts files
        'src/**/*.{js,ts}',
        // the default
        /\.(vue|svelte|[jt]sx|mdx?|astro|elm|php|phtml|html)($|\?)/,
      ],
    },
  },
});

```

**Comment by kingtimm** [comment]
Thank you! Your hint pointed me in the right direction - it wasn't including `src/components/ui/button/index.ts`. 

Changing the `uno.config.ts` to: 

```ts
content: {
    pipeline: {
      include: [
        // include js/ts files
        "**/*.{js,ts}",
        // the default
        /\.(vue|svelte|[jt]sx|mdx?|astro|elm|php|phtml|html)($|\?)/,
      ],
    },
  },
```
...allowed it to work. Thank you!
